Map<String, String> appStrings  = {
   'AAVE' : 'Aave',
   'ALGO' : 'ALGO',
   'BCH' : 'Bitcoin Cash',
   'BTC' : 'Bitcoin',
   'BUSD' : 'Binance USD',
   'DGLD' : 'DGLD',
   'ENJ' : 'Enjin Coin',
   'ETH' : 'Ethereum',
   'EUR' : 'Euros',
   'GBP' : 'British Pounds',
   'LEND' : 'Aave Coin',
   'LTC' : 'Litecoin',
   'OGN' : 'Origin Protocol',
   'PAX' : 'Paxos Standard',
   'TRY' : 'Trias',
   'USD' : 'US Dollars',
   'USDT' : 'Tether',
   'WDGLD' : 'wrapped-DGLD',
   'XLM' : 'Stellar',
   'XRP' : 'XRP',
   'YFI' : 'yearn.finance',
};
